# Generated by Django 3.0.4 on 2020-04-24 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=100, null=True)),
                ('sweet_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('oil_type', models.CharField(max_length=100)),
                ('ghee_type', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=1, default=1, max_digits=10)),
                ('amount', models.FloatField(default=0.0, max_length=20)),
                ('image', models.ImageField(upload_to='Sweet_Types')),
                ('is_delivered', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('sweet_name', 'category', 'oil_type', 'ghee_type')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='cart.CartItems')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whether_added', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('pincode', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
