# Generated by Django 3.0.4 on 2020-04-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200424_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
