# Generated by Django 3.0.4 on 2020-04-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_orders'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('sweet_name', 'category', 'oil_type', 'ghee_type', 'is_ordered', 'order_id')},
        ),
    ]
