# Generated by Django 3.0.4 on 2020-04-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20200424_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
