# Generated by Django 3.0.4 on 2020-04-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20200424_2216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('sweet_name', 'category', 'oil_type', 'ghee_type', 'order_id')},
        ),
    ]
