# Generated by Django 3.0.4 on 2020-04-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20200424_2249'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('user', 'sweet_name', 'category', 'oil_type', 'ghee_type', 'order_id', 'is_ordered')},
        ),
    ]
