# Generated by Django 3.0.4 on 2020-04-24 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20200424_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 18, 57, 31, 121493, tzinfo=utc)),
        ),
    ]
