# Generated by Django 3.0.4 on 2020-04-25 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20200425_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 12, 46, 46, 411862, tzinfo=utc)),
        ),
    ]
