# Generated by Django 3.0.4 on 2020-04-25 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20200425_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 18, 32, 48, 56804, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 18, 32, 48, 55807, tzinfo=utc)),
        ),
    ]
