# Generated by Django 3.0.4 on 2020-04-25 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20200426_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 19, 18, 3, 825561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 19, 18, 3, 827594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 19, 18, 3, 827594, tzinfo=utc)),
        ),
    ]
