# Generated by Django 3.0.4 on 2020-04-26 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_auto_20200426_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 16, 1, 10, 290649, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 16, 1, 10, 292643, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 16, 1, 10, 292643, tzinfo=utc)),
        ),
    ]
