# Generated by Django 3.0.4 on 2020-04-26 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20200426_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_itemcancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 19, 4, 24, 734854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 19, 4, 24, 736849, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 19, 4, 24, 736849, tzinfo=utc)),
        ),
    ]
