# Generated by Django 3.0.4 on 2020-04-26 19:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_auto_20200427_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 19, 50, 16, 835705, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 19, 50, 16, 838666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 19, 50, 16, 838666, tzinfo=utc)),
        ),
    ]
