# Generated by Django 3.0.4 on 2020-04-26 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_auto_20200427_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_complete_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 19, 59, 34, 622355, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 19, 59, 34, 624350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 19, 59, 34, 624350, tzinfo=utc)),
        ),
    ]
