# Generated by Django 3.0.4 on 2020-04-28 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_auto_20200428_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 16, 38, 20, 65560, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 16, 38, 20, 67555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 16, 38, 20, 67555, tzinfo=utc)),
        ),
    ]
