# Generated by Django 3.0.6 on 2021-05-06 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_auto_20200428_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 10, 40, 30, 355984, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 10, 40, 30, 357939, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 10, 40, 30, 357939, tzinfo=utc)),
        ),
    ]
