# Generated by Django 3.0.6 on 2021-05-06 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_auto_20210506_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 12, 12, 45, 229009, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 12, 12, 45, 232004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 12, 12, 45, 232004, tzinfo=utc)),
        ),
    ]
